up

diff --git a/.kickers/kick b/.kickers/kick
--- a/.kickers/kick
+++ b/.kickers/kick
@@ -56,21 +56,21 @@ done
 # Reduce Apple Terminal cursor ghosting
 #
 
-exec 3>&1 4>&2
-exec >/tmp/git.log 2>&1
+# exec 3>&1 4>&2
+# exec >/tmp/git.log 2>&1
 
-cleanup() {
-    set +x
-    exec 1>&3 2>&4
-    exec 3>&- 4>&-
-    cat /tmp/git.log
+# cleanup() {
+#     set +x
+#     exec 1>&3 2>&4
+#     exec 3>&- 4>&-
+#     cat /tmp/git.log
 
-    if [ "$TERM_PROGRAM" = 'Apple_Terminal' ]; then
-        printf '\e[8;24;80t'
-    fi
-}
+#     if [ "$TERM_PROGRAM" = 'Apple_Terminal' ]; then
+#         printf '\e[8;24;80t'
+#     fi
+# }
 
-trap cleanup EXIT ERR SIGINT
+# trap cleanup EXIT ERR SIGINT
 
 if [ "$QUIET" -ne 1 ]; then
     set -x
